### ISSUE TITLE
Update the content headers for Github and Events to better fit the layout of the site. 

### ISSUE THREAD

**Issue by gullapalli9482** [P2PHackClub/website#44]
At the bottom of the website , info regarding the hacktoberfest website, isn;t visible since it wasn't added to the footer text part.
everything is properly written but , it isn't visible since it got blended with the background, causing ambiguity on what the "here" is about .

**Comment by S3cBar0n** [comment]
Hey @gullapalli9482!

Per our conversation, the events div has already been fixed in a previous PR, however, you wanted to take a crack at fixing the headers and making them better fit the site. This Issue has been modified for that specifically and you are now assigned this issue.

Good luck and happy hacking!

**Comment by thatrobotdev** [comment]
Hello! Looks like on the current site the content headers look really good! If anything, we might want to create styling for some subheaders inside of individual event boxes.

![image](https://user-images.githubusercontent.com/18013689/139626674-2aba6ccd-0e7c-4263-b7aa-19c6fd16d7e0.png)

For now, I've closed #50 for being out of date, but if you want to take a crack at this again for the new version of the site, please let me know!

Thank you so much for your contribution.
